name: CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: write
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 7bc6b316-1f77-4eae-8191-dce56ea0c75a
          heroku_app_name: housing-db
          heroku_email: abdiazizmohamed401@gmail.com